export const routes = [
  {
    label: "React JS",
    to: "/docs/reactjs",
    icon: null,
    children: [
      {
        label: "Components",
        to: "/docs/reactjs/components",
        icon: null,
        children: [
          {
            label: "React Portal",
            to: "/docs/reactjs/components/react-portal",
            brief: "",
            icon: null,
          },
          {
            label: "Pagination",
            to: "/docs/reactjs/components/Pagination",
            brief: "",
            icon: null,
          },
        ],
      },
      {
        label: "Hooks",
        to: "/docs/reactjs/hooks",
        icon: null,
        children: [
          {
            label: "useAsyncInitialize()",
            to: "/docs/reactjs/hooks/useAsyncInitialize",
            brief: "",
            icon: null,
          },
          {
            label: "useCookie()",
            to: "/docs/reactjs/hooks/useCookie",
            brief: "",
            icon: null,
          },
          {
            label: "useCopyToClipboard()",
            to: "/docs/reactjs/hooks/useCopyToClipboard",
            brief: "",
            icon: null,
          },
          {
            label: "useDebounce()",
            to: "/docs/reactjs/hooks/useDebounce",
            brief: "",
            icon: null,
          },
          {
            label: "useFetch()",
            to: "/docs/reactjs/hooks/useFetch",
            brief: "",
            icon: null,
          },
          {
            label: "useMqtt()",
            to: "/docs/reactjs/hooks/useMqtt",
            brief: "",
            icon: null,
          },
          {
            label: "useOutsideClick()",
            to: "/docs/reactjs/hooks/useOutsideClick",
            brief: "",
            icon: null,
          },
          {
            label: "usePageVisibility()",
            to: "/docs/reactjs/hooks/usePageVisibility",
            brief: "",
            icon: null,
          },
          {
            label: "usePagination()",
            to: "/docs/reactjs/hooks/usePagination",
            brief: "",
            icon: null,
          },
          {
            label: "useWindowSize()",
            to: "/docs/reactjs/hooks/useWindowSize",
            brief: "",
            icon: null,
          },
          {
            label: "usePrevious()",
            to: "/docs/reactjs/hooks/usePrevious",
            brief: "",
            icon: null,
          },
        ],
      },
      {
        label: "Functions",
        to: "/docs/reactjs/functions",
        icon: null,
        children: [
          {
            label: "buildCurrentUrlWithParameter()",
            to: "/docs/reactjs/functions/buildCurrentUrlWithParameter",
            brief: "",
            icon: null,
          },
          {
            label: "copyText()",
            to: "/docs/reactjs/functions/copyText",
            brief: "",
            icon: null,
          },
          {
            label: "dowloadPublic()",
            to: "/docs/reactjs/functions/dowloadPublic",
            brief: "",
            icon: null,
          },
          {
            label: "fetchAndUnzipFromCDN()",
            to: "/docs/reactjs/functions/fetchAndUnzipFromCDN",
            brief: "",
            icon: null,
          },
          {
            label: "fileToGenerativePart()",
            to: "/docs/reactjs/functions/fileToGenerativePart",
            brief: "",
            icon: null,
          },
          {
            label: "haversine()",
            to: "/docs/reactjs/functions/haversine",
            brief: "",
            icon: null,
          },
          {
            label: "readFileJsonCsv()",
            to: "/docs/reactjs/functions/readFileJsonCsv",
            brief: "",
            icon: null,
          },
          {
            label: "readFileZip()",
            to: "/docs/reactjs/functions/readFileZip",
            brief: "",
            icon: null,
          },
          {
            label: "readQRFromImage()",
            to: "/docs/reactjs/functions/readQRFromImage",
            brief: "",
            icon: null,
          },
          {
            label: "removeDuplicateElement()",
            to: "/docs/reactjs/functions/removeDuplicateElement",
            brief: "",
            icon: null,
          },
          {
            label: "removeVietnameseTones()",
            to: "/docs/reactjs/functions/removeVietnameseTones",
            brief: "",
            icon: null,
          },
          {
            label: "plateform()",
            to: "/docs/reactjs/functions/plateform",
            brief: "",
            icon: null,
          },
        ],
      },
    ],
  },
];
